{ pkgs, lib, ...}: 

{
  wayland.windowManager.hyprland = {
    # Allow Home Manager to configure Hyprland
    enable = true;

    settings = {
      autogenerated = 0;

      "$mod" = "SUPER";

      monitor = "preferred,auto,auto";

      # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
      input = {
        kb_layout = ["us"];
        kb_variant = "";
        kb_model = "";
        kb_options = "";
        kb_rules = "";

        follow_mouse = 1;

      touchpad = {
        natural_scroll = true;
      };

        sensitivity = 0; # -1.0 to 1.0, 0 means no modification.
     };
    };
  };
}
